
[package]
name = "rust_onepiece"
version = "0.0.1"
edition = "2021"

[dependencies]
axum = "0.8.4"
diesel = { version = "2.2.12", features = ["postgres", "r2d2"] }
diesel_migrations = "2.2.0"
dotenvy = "0.15.7"
env_logger = "0.11.8"
postgres = "0.19.10"
serde = "1.0.219"
serde_json = "1.0.142"
tokio = { version = "1.47.1", features = ["full"] }
uuid = { version = "1.17.0", features = ["v4", "serde"] }
